name: Build & Test

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:

    name: build-and-test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest]

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.x
            7.x
            8.x
            9.x

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build (Debug)
        run: dotnet build -c Debug

      - name: Build (Release)
        run: dotnet build -c Release

      - name: Test (Debug)
        run: |
          dotnet test -c Debug --no-build
          echo "Tests completed"

      - name: Test (Release)
        run: dotnet test -c Release --no-build

      - name: Test (Debug, AVX2=0)
        env:
          DOTNET_EnableAVX2: "0"
        run: dotnet test -c Debug --no-build

      - name: Test (Release, AVX2=0)
        env:
          DOTNET_EnableAVX2: "0"
        run: dotnet test -c Release --no-build

      - name: Test (Debug, HWIntrinsic=0)
        env:
          DOTNET_EnableHWIntrinsic: "0"
        run: dotnet test -c Debug --no-build

      - name: Test (Release, HWIntrinsic=0)
        env:
          DOTNET_EnableHWIntrinsic: "0"
        run: dotnet test -c Release --no-build
