name: Build & Test

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:

    name: build-and-test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.x
            7.x
            8.x
            9.x

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build (Debug)
        run: dotnet build -c Debug

      - name: Build (Release)
        run: dotnet build -c Release

      - name: Test (Debug)
        run: dotnet test -c Debug --no-build

      - name: Test (Release)
        run: dotnet test -c Release --no-build

      - name: Test (Debug, Avx2=Disabled, Windows)
        if: runner.os == 'Windows'
        run:
          $env:COMPlus_EnableAVX2="0"
          dotnet test -c Debug --no-build

      - name: Test (Release, Avx2=Disabled, Windows)
        if: runner.os == 'Windows'
        run:
          $env:COMPlus_EnableAVX2="0"
          dotnet test -c Release --no-build

      - name: Test (Debug, Avx2=Disabled, Sse2=Disabled, Windows)
        if: runner.os == 'Windows'
        run:
          $env:COMPlus_EnableAVX2="0"
          $env:COMPlus_EnableSSE2="0"
          dotnet test -c Debug --no-build

      - name: Test (Release, Avx2=Disabled, Sse2=Disabled, Windows)
        if: runner.os == 'Windows'
        run:
          $env:COMPlus_EnableAVX2="0"
          $env:COMPlus_EnableSSE2="0"
          dotnet test -c Release --no-build

      - name: Test (Debug, Avx2=Disabled, Linux)
        if: runner.os == 'Ubuntu'
        run: |
          export COMPlus_EnableAVX2=0
          dotnet test -c Debug --no-build

      - name: Test (Release, Avx2=Disabled, Linux)
        if: runner.os == 'Ubuntu'
        run: |
          export COMPlus_EnableAVX2=0
          dotnet test -c Release --no-build

      - name: Test (Debug, Avx2=Disabled, Sse2=Disabled, Linux)
        if: runner.os == 'Ubuntu'
        run: |
          export COMPlus_EnableAVX2=0
          export COMPlus_EnableSSE2=0
          dotnet test -c Debug --no-build

      - name: Test (Release, Avx2=Disabled, Sse2=Disabled, Linux)
        if: runner.os == 'Ubuntu'
        run: |
          export COMPlus_EnableAVX2=0
          export COMPlus_EnableSSE2=0
          dotnet test -c Release --no-build
