<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="BenchmarkDotNet.Attributes"/>
    <Using Include="BenchmarkDotNet.Running"/>
    <Using Include="Ramstack.Globbing"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Ramstack.Globbing\Ramstack.Globbing.csproj"/>
  </ItemGroup>
</Project>
